# Generated by Django 6.0 on 2025-12-24 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('VIEW', 'عرض تقرير'), ('SEARCH', 'بحث'), ('PRINT', 'طباعة تقرير'), ('EXPORT', 'تصدير بيانات'), ('DENIED', 'محاولة وصول مرفوضة')], max_length=10, verbose_name='الإجراء')),
                ('target_object', models.CharField(blank=True, help_text='Report ID, Search Query, etc.', max_length=255, verbose_name='الهدف')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات الأنشطة',
                'ordering': ['-timestamp'],
            },
        ),
    ]
