# Generated by Django 6.0 on 2025-12-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال'),
        ),
    ]
