# Generated by Django 6.0 on 2025-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('MIL', 'عسكري'), ('CIV', 'مدني')], default='CIV', max_length=10, verbose_name='الرتبة'),
        ),
    ]
