# Generated by Django 5.0.3 on 2025-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'تسجيل دخول'), ('LOGOUT', 'تسجيل خروج'), ('VIEW', 'عرض تقرير'), ('SEARCH', 'بحث'), ('PRINT', 'طباعة تقرير'), ('EXPORT', 'تصدير بيانات'), ('DENIED', 'محاولة وصول مرفوضة'), ('OTHER', 'أخرى')], max_length=10, verbose_name='الإجراء'),
        ),
    ]
