# Generated by Django 5.0.3 on 2025-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_useractionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام (Admin)'), ('MANAGER', 'مدير (System Manager)'), ('ANALYST', 'محلل (Analyst)')], default='ANALYST', max_length=10, verbose_name='الدور الوظيفي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='الرقم الوظيفي'),
        ),
    ]
