# Generated by Django 5.0.3 on 2025-12-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_role_alter_user_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='رقم الهوية الوطنية'),
        ),
    ]
