# Generated by Django 6.0 on 2025-12-24 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('original_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='الرابط الأصلي')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('classification', models.CharField(choices=[('U', 'غير مصنف'), ('R', 'مقيد'), ('C', 'سري'), ('S', 'سري للغاية'), ('TS', 'للغاية سري')], default='U', max_length=2, verbose_name='التصنيف الأمني')),
                ('credibility_score', models.IntegerField(default=0, verbose_name='درجة المصداقية')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='تحليل المشاعر')),
            ],
            options={
                'verbose_name': 'تقرير استخباراتي',
                'verbose_name_plural': 'تقارير الاستخبارات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المصدر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='رابط المصدر')),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('API', 'API Endpoint'), ('SOC', 'Social Media'), ('MAN', 'إدخال يدوي')], default='RSS', max_length=10, verbose_name='نوع المصدر')),
                ('reliability_score', models.IntegerField(default=50, help_text='من 0 إلى 100', verbose_name='درجة الموثوقية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'مصدر',
                'verbose_name_plural': 'المصادر',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('entity_type', models.CharField(choices=[('PER', 'شخص'), ('ORG', 'منظمة'), ('LOC', 'موقع'), ('EVT', 'حدث')], max_length=3, verbose_name='النوع')),
                ('reports', models.ManyToManyField(related_name='entities', to='intelligence.intelligencereport', verbose_name='التقارير المرتبطة')),
            ],
            options={
                'verbose_name': 'كيان',
                'verbose_name_plural': 'الكيانات',
            },
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='intelligence.source', verbose_name='المصدر'),
        ),
    ]
