# Generated by Django 6.0 on 2025-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='related_reports',
            field=models.ManyToManyField(blank=True, to='intelligence.intelligencereport', verbose_name='تقارير ذات صلة'),
        ),
    ]
