# Generated by Django 6.0 on 2025-12-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_intelligencereport_related_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(blank=True, help_text='مثال: صحف أمريكية، وكالات عالمية', max_length=100, verbose_name='التصنيف/الدولة'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('RSS', 'RSS Feed'), ('API', 'API Endpoint'), ('SOC', 'Social Media'), ('WEB', 'موقع إخباري'), ('MAN', 'إدخال يدوي'), ('OTH', 'أخرى')], default='RSS', max_length=10, verbose_name='نوع المصدر'),
        ),
    ]
