# Generated by Django 5.0.3 on 2025-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_source_category_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='translated_content',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى المترجم'),
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='translated_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان المترجم'),
        ),
    ]
