# Generated by Django 5.0.3 on 2025-12-27 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_intelligencereport_translated_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_reports', to=settings.AUTH_USER_MODEL, verbose_name='المفضلة'),
        ),
    ]
