# Generated by Django 5.0.3 on 2025-12-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_intelligencereport_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='original_language',
            field=models.CharField(default='en', max_length=10, verbose_name='اللغة الأصلية'),
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'قيد المعالجة'), ('COMPLETED', 'تمت المعالجة'), ('FAILED', 'فشل المعالجة')], default='PENDING', max_length=20, verbose_name='حالة المعالجة'),
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='severity',
            field=models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج/طارئ')], default='LOW', max_length=10, verbose_name='درجة الخطورة'),
        ),
        migrations.CreateModel(
            name='IntelligenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('level', models.CharField(choices=[('INFO', 'معلومة'), ('WARNING', 'تحذير'), ('CRITICAL', 'خطر/حرج')], default='INFO', max_length=10, verbose_name='المستوى')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='intelligence.intelligencereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
