# Generated by Django 5.0.3 on 2025-12-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_intelligencereport_original_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='topic',
            field=models.CharField(choices=[('MILITARY', 'عسكري وحربي'), ('SECURITY', 'أمني'), ('ARMAMENT', 'تسليح'), ('INTEL', 'استخباراتي'), ('MIL_TECH', 'تكنولوجيا عسكرية'), ('MEDICAL', 'طبي/أوبئة'), ('OTHER', 'عام/أخرى')], default='OTHER', max_length=20, verbose_name='التصنيف الموضوعي'),
        ),
    ]
