# Generated by Django 5.0.3 on 2025-12-27 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_intelligencereport_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: الأزمة اليمنية، تسليح الحوثي', max_length=200, verbose_name='اسم التنبيه')),
                ('keywords', models.TextField(help_text='افصل بين الكلمات بفاصلة. مثال: يمن, حوثي, صاروخ', verbose_name='الكلمات المفتاحية')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='المنطقة/الدولة')),
                ('severity_level', models.CharField(choices=[('HIGH', 'عالي'), ('CRITICAL', 'حرج/طارئ')], default='CRITICAL', max_length=10, verbose_name='مستوى الخطورة المطلوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قاعدة تنبيه حرج',
                'verbose_name_plural': 'قواعد التنبيهات الحرجة',
            },
        ),
        migrations.AddField(
            model_name='intelligencenotification',
            name='alert_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.criticalalertrule', verbose_name='قاعدة التنبيه'),
        ),
    ]
