# Generated by Django 5.0.3 on 2025-12-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_criticalalertrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='جزء من الرابط أو اسم المصدر (مثال: sports, health)', max_length=100, unique=True, verbose_name='الكلمة المحظورة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الحظر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نطاق/مصدر محظور',
                'verbose_name_plural': 'قائمة حظر المصادر',
            },
        ),
        migrations.CreateModel(
            name='SovereignTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_term', models.CharField(max_length=100, unique=True, verbose_name='المصطلح الإنجليزي')),
                ('arabic_translation', models.CharField(max_length=100, verbose_name='الترجمة العربية السيادية')),
                ('is_regex', models.BooleanField(default=False, verbose_name='تعبير نمطي (Regex)')),
                ('category', models.CharField(choices=[('MILITARY', 'عسكري'), ('POLITICAL', 'سياسي'), ('GENERAL', 'عام')], default='GENERAL', max_length=50, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مصطلح سيادي',
                'verbose_name_plural': 'قاموس المصطلحات السيادية',
            },
        ),
    ]
