# Generated by Django 5.0.3 on 2025-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_ignoredsource_sovereignterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('keywords', models.TextField(help_text='مفصولة بفاصلة. وجود أي منها يفعل القاعدة جزئياً.', verbose_name='الكلمات المفتاحية (OR)')),
                ('required_keywords', models.TextField(blank=True, help_text='مفصولة بفاصلة. يجب توفر إحداها على الأقل لتفعيل القاعدة.', verbose_name='كلمات الشرط (AND)')),
                ('classification', models.CharField(choices=[('U', 'غير مصنف'), ('R', 'مقيد'), ('C', 'سري'), ('S', 'سري للغاية'), ('TS', 'للغاية سري')], max_length=2, verbose_name='التصنيف الناتج')),
                ('severity', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'عالي'), ('CRITICAL', 'حرج/طارئ')], default='MEDIUM', max_length=10, verbose_name='درجة الخطورة الناتجة')),
                ('topic', models.CharField(default='GENERAL_INTEL', max_length=50, verbose_name='الموضوع الناتج')),
                ('weight', models.IntegerField(default=10, help_text='القواعد ذات الوزن الأعلى تطبق أولاً', verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'قاعدة تصنيف سيادي',
                'verbose_name_plural': 'قواعد التصنيف الآلي',
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='EntityExtractionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, unique=True, verbose_name='النمط/الكلمة')),
                ('entity_type', models.CharField(choices=[('PER', 'شخص'), ('ORG', 'منظمة'), ('LOC', 'موقع'), ('EVT', 'حدث')], max_length=3, verbose_name='نوع الكيان')),
            ],
            options={
                'verbose_name': 'نمط استخراج كيان',
                'verbose_name_plural': 'أنماط استخراج الكيانات',
            },
        ),
    ]
