# Generated by Django 5.0.3 on 2025-12-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0010_classificationrule_entityextractionpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencereport',
            name='content_ar',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى (عربي)'),
        ),
        migrations.AddField(
            model_name='intelligencereport',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان (عربي)'),
        ),
    ]
