# Generated by Django 5.0.3 on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0012_seed_default_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, unique=True, verbose_name='نص القيد')),
                ('constraint_type', models.CharField(choices=[('KEYWORD', 'كلمة'), ('PHRASE', 'جملة'), ('TITLE', 'عنوان')], default='KEYWORD', max_length=20, verbose_name='نوع القيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قيد بحث استدلالي',
                'verbose_name_plural': 'قيود البحث الاستدلالية',
                'ordering': ['-created_at'],
            },
        ),
    ]

