# Generated by Django 6.0 on 2025-12-25 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Protocol', max_length=100, verbose_name='اسم الإعداد')),
                ('system_prompt', models.TextField(default='أنت محلل استخباراتي استراتيجي ذو خبرة عالية. مهمتك هي تقديم تحليلات دقيقة، موضوعية، وشاملة بناءً على المعلومات المتاحة. اتبع المنهجية الاستقرائية في التحليل. ركز على التهديدات الأمنية، الجيوسياسية، والاقتصادية.', help_text='التعليمات الأساسية التي تحكم سلوك الوكيل. مثال: أنت محلل استخباراتي خبير...', verbose_name='التعليمات العليا (System Prompt)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='agent_docs/', verbose_name='الملف')),
                ('content_text', models.TextField(blank=True, help_text='المحتوى المستخرج من الملف للبحث', verbose_name='المحتوى النصي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان المحادثة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'الوكيل الذكي'), ('system', 'النظام')], max_length=20)),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citations', models.JSONField(blank=True, null=True, verbose_name='المراجع/المصادر')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intelligence_agent.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
