# Generated by Django 5.0.3 on 2025-12-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_agent', '0002_alter_agentinstruction_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='مرفق'),
        ),
    ]
