"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY MUST be set via environment variable
SECRET_KEY = os.environ.get('SECRET_KEY')

# Fallback to development key only if DEBUG is True and SECRET_KEY is not set
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

if not SECRET_KEY:
    if DEBUG:
        # Development fallback - only used when DEBUG=True
        SECRET_KEY = 'django-insecure-7kbmjh&#j#r5525=%60fryv1c9@#%4p9rw_wmyq4n%uyu&%28p'
    else:
        # Production: SECRET_KEY is required
        raise ValueError(
            "SECRET_KEY environment variable is required in production. "
            "Set DEBUG=False only after setting SECRET_KEY."
        )

# SECURITY WARNING: don't run with debug turned on in production!
# Configure ALLOWED_HOSTS based on environment
ALLOWED_HOSTS = []

if not DEBUG:
    # Production: Parse ALLOWED_HOSTS from environment variable
    allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
    if allowed_hosts_env:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
    
    # Auto-detect from platform-specific environment variables
    if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
        ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN'))
    if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
        ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))
    if os.environ.get('VERCEL_URL'):
        ALLOWED_HOSTS.append(os.environ.get('VERCEL_URL'))
    
    # Remove duplicates while preserving order
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
    
    # If still empty in production, raise an error
    if not ALLOWED_HOSTS:
        raise ValueError(
            "ALLOWED_HOSTS must be configured in production. "
            "Set the ALLOWED_HOSTS environment variable with comma-separated domains."
        )
else:
    # Development: Allow local access
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'core',
    'intelligence',
    'intelligence_agent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Configure database from DATABASE_URL environment variable (for PostgreSQL)
# Falls back to SQLite for development
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production: Use DATABASE_URL (PostgreSQL, MySQL, etc.)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', 600)),
            conn_health_checks=True,
            ssl_require=os.environ.get('DB_SSL_REQUIRE', 'False').lower() in ('true', '1', 'yes')
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Set connection timeout for database operations
DATABASES['default'].setdefault('OPTIONS', {})
if 'sqlite' not in DATABASES['default']['ENGINE']:
    # PostgreSQL connection timeout options
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', 10)),
    })


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# Custom user model
AUTH_USER_MODEL = 'core.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'ar')

TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Riyadh')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Trusted Origins (for production HTTPS)
CSRF_TRUSTED_ORIGINS = []
if not DEBUG:
    csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins_env:
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]
    
    # Auto-detect from platform-specific environment variables
    if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
        CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ.get('RAILWAY_PUBLIC_DOMAIN')}")
    if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
        CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ.get('RENDER_EXTERNAL_HOSTNAME')}")
    if os.environ.get('RENDER_EXTERNAL_URL'):
        CSRF_TRUSTED_ORIGINS.append(os.environ.get('RENDER_EXTERNAL_URL'))
    if os.environ.get('VERCEL_URL'):
        CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ.get('VERCEL_URL')}")
    
    # Remove duplicates while preserving order
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() in ('true', '1', 'yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
